### ISSUE TITLE
Is there an example of how to do AD through `if` statements?

### ISSUE THREAD

**Issue by xiaodaigh** [GiggleLiu/NiLang.jl#12]
For example how to auto-differentiate through the leaky ReLU defined as

```julia
function relu(x)
  if x > 0
    x
  else
    0.01x
  end
end
```

**Comment by GiggleLiu** [comment]
This example contains an if statement.
https://giggleliu.github.io/NiLang.jl/dev/examples/sparse/

For more sophisticated cases, you may want to specify the post condition.
It is introduced in our paper https://arxiv.org/abs/2003.04617

**Comment by GiggleLiu** [comment]
The condition statement of if must contain two parts.
 A precondition and post condition, if post condition is same as precondition, you can omit it by putting a ~ as the place holder.
Your leaky relu example is not reversible, it should contain two parameters as inputs.

**Comment by GiggleLiu** [comment]
```julia repl
julia> using NiLang

julia> @i function relu(y!, x)
         if (x > 0, ~)
           y! += identity(x)
         else
           y! += 0.01 * x
         end
       end

julia> relu(0.0, -2.0)
(-0.02, -2.0)
```
