### ISSUE TITLE
auto-preallocation?

### ISSUE THREAD

**Issue by johnnychen94** [GiggleLiu/NiLang.jl#75]
Sometimes it's tedious and not-so-funny to figure out the shape and type of every output arguments. I guess it makes sense to introduce something like

```julia
function allocate_output(::typeof(imul!), A::AbstractMatrix, B::AbstractMatrix)
    AT = Base.return_types(*, (typeof(A), typeof(B))[1]
    out = fill!(AT(undef, size(A, 1), size(B, 2)), zero(eltype(AT)))
    return (out, )
end
```

as a part of `@i` protocol?

**Comment by GiggleLiu** [comment]
This interface is called `alloc` in NiLang, it is implemented here:
https://github.com/GiggleLiu/NiLang.jl/blob/f24036c478ace467ae71f630e1db2698e38fd64d/src/macros.jl#L15
Check here for examples: https://github.com/GiggleLiu/NiLang.jl/blob/master/test/macros.jl

**Comment by johnnychen94** [comment]
Ha so this is already implemented. Is this some kind of standard that we can reliably use for any (or most) reversible function

**Comment by GiggleLiu** [comment]
> Ha so this is already implemented. Is this some kind of standard that we can reliably use for any (or most) reversible function?

I think so, when the output data structure is complicated, it can be useful to write an alloc function.

**Comment by johnnychen94** [comment]
In this case then there's nothing left I think.

Ping @jieli-matrix as she might be interested to know this.
